apiVersion: v1
kind: Namespace
metadata:
  name: sumon
---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: hello
  namespace: sumon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      imagePullSecrets:
      - name: sumondocker
      containers:
        - name: hello
          image: localhost:5000/test
          imagePullPolicy: Always
          ports:
          - containerPort: 80
      restartPolicy: Always
---

kind: Service
apiVersion: v1
metadata:
  name: hello
  namespace: sumon
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 31000
  selector:
    app: hello

---

apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5naXRsYWIuY29tIjp7InVzZXJuYW1lIjoibXlhdDg2QGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiXzFGdU5RN3Jqblh3bzg2aHBDRGsiLCJlbWFpbCI6Im15YXQ4NkBnbWFpbC5jb20iLCJhdXRoIjoiYlhsaGREZzJRR2R0WVdsc0xtTnZiVHBmTVVaMVRsRTNjbXB1V0hkdk9EWm9jRU5FYXc9PSJ9fX0=
kind: Secret
metadata:
  name: sumondocker
  namespace: sumon
type: kubernetes.io/dockerconfigjson